ScrapLocker/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/login',   to: 'sessions#new',         via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

ScrapLocker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ScrapLocker/app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	has_secure_password

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.digest(User.new_remember_token)
	end
	
end

ScrapLocker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

ScrapLocker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
	
end

ScrapLocker/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		if signed_in?
			@greeting = "Welcome"
		end
	end

	def help
	end

	def about
	end

	def contact
	end
	
end

ScrapLocker/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update, :show]
	before_action :admin_user,     only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.where(id: params[:id]).first
		if @user.nil?
			render template: 'static_pages/404'
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		# Before filters

		def correct_user
			@user = User.where(id: params[:id]).first
			render template: 'static_pages/404' unless current_user?(@user)
			#redirect_to(root_url) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

ScrapLocker/app/helpers/application_helper.rb
module ApplicationHelper
end

ScrapLocker/app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token  = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
		store_location
		redirect_to signin_url, notice: "Please sign in."
		end
	end

	def sign_out
		current_user.update_attribute(:remember_token,
		User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

end

ScrapLocker/app/helpers/users_helper.rb
module UsersHelper
end

ScrapLocker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrapLocker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
	<%= render 'nav_components/site_header' %>
	<%= render 'nav_components/site_navbar' %>

  </head>

  <body>
  	<div id="body-content">
    <%= yield %>
    </div>
  </body>
</html>

ScrapLocker/app/views/nav_components/_site_header.html.erb
<header id="site_banner_lg">
    	<div class="container-fluid">
			<div class="row zsx">
				<div class="col-lg-12 animated lightSpeedIn">
					<p class="vcenter">
					<h1><i class="fa fa-bomb fa-lg"></i>ScrapLocker</h1>
					<h3>Plan. Do. Share.</h3>
					</p>
				</div>
			</div>
		</div>
</header>

ScrapLocker/app/views/nav_components/_site_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a id="navbar-brand-tag" class="navbar-brand" href="<%= root_path %>"><span class="glyphicon glyphicon-home"></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
                  <li><a href="#">My Scraps</a></li>
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse<b class="caret"></b></a>
                     <ul class="dropdown-menu">
                        <li><a href="#">Trending</a></li>
                        <li><a href="#">Recent</a></li>
                        <li><a href="#">Friends</a></li>
                     </ul>
                  </li>
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories<b class="caret"></b></a>
                     <ul class="dropdown-menu">
                        <li><a href="#">Movies</a></li>
                        <li><a href="#">Foods</a></li>
                        <li><a href="#">Bars</a></li>
                     </ul>
                  </li>
    </ul>
    <div class="col-sm-4 col-md-4">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
        </form>
    </div>
    <ul id="navbar-right-fragment" class="nav navbar-nav navbar-right">
                  <% if not signed_in? %>
                  	 <li><a href="<%= signup_path %>">Sign Up</a></li>
                     <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in <b class="caret"></b></a>
                     <ul id="navbar-session-dropdown" class="dropdown-menu">
                        <li>
                           <div class="row">
                              <div class="col-md-12">
									<%= bootstrap_form_for(:session, url: sessions_path) do |f| %>
										<li><%= f.text_field :email %></li>
										<li><%= f.password_field :password %></li>
										<li><%= f.submit "Sign in", class: "btn btn-large btn-primary" %></li>
									<% end %>
                              </div>
                           </div>
                        </li>
                     </ul>
                     </li>
                  <% else %>
                    <li><a href="<%= user_path(@user.id) %>"><%= @user.name %></a></li>
					<li><%= link_to "Logout", signout_path, method: "delete" %></li>
                  <% end %>
                  
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

ScrapLocker/app/views/static_pages/404.html.erb
<h1>404</h1>

ScrapLocker/app/views/static_pages/home.html.erb
<h1>Welcome to ScrapLocker!</h1>
<h4>(Previously Rigby's List)</h4>

<h5>Debugging Info</h5>
<h6>User is signed in? :: <%= signed_in? %></h6>

<br><p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquet, ex quis ultrices faucibus, eros dolor elementum dui, nec convallis velit turpis at odio. Sed ac tortor mauris. Quisque vel enim maximus, facilisis leo eget, tincidunt enim. Proin rhoncus vitae odio in consectetur. Aenean aliquet risus erat. Suspendisse finibus turpis non porta luctus. Vestibulum sit amet imperdiet ipsum. Duis semper, magna eget pretium convallis, lectus dui vulputate eros, nec maximus neque arcu in velit.

<br><p>
Mauris et elementum velit. Nulla ultricies massa eu quam blandit dictum nec ut massa. Donec ac elit sit amet nibh sagittis gravida eget quis eros. Maecenas aliquet, nibh vel auctor aliquam, lacus nisi aliquam magna, non maximus eros nisi at sapien. Ut risus odio, rhoncus eu neque et, faucibus faucibus mi. Nulla a venenatis lorem, et laoreet tortor. Vestibulum eget finibus ipsum, vel consectetur nibh. Donec condimentum ante eget laoreet cursus. Sed sollicitudin urna nec purus sagittis, ac molestie turpis condimentum. Etiam sed risus felis.

<br><p>
Vivamus euismod rutrum ipsum quis sagittis. Vivamus a interdum eros. Donec vehicula tortor ac libero ultrices fermentum. Integer congue interdum ipsum non lacinia. Quisque sed volutpat velit. Mauris gravida ipsum eu mauris congue, at auctor enim gravida. Suspendisse vel quam at lacus condimentum accumsan. In dapibus, dui sed rhoncus volutpat, nunc dolor rutrum justo, at elementum augue nisi sed dolor. Nam viverra leo in dui pellentesque, a luctus ante dignissim. Pellentesque hendrerit faucibus ornare. Etiam pharetra, quam nec pellentesque efficitur, lectus metus ultricies neque, vitae sodales turpis nisi sed ligula. Pellentesque nec pharetra ante. Sed vitae dui cursus, pellentesque risus vel, pretium augue.

<br><p>
Cras scelerisque dictum auctor. Nunc egestas leo a rhoncus auctor. Donec blandit aliquam tortor, fermentum ultrices dolor aliquam ac. Aenean sed libero laoreet, viverra magna posuere, dignissim nisl. Sed purus leo, congue vitae nulla quis, luctus cursus lectus. Suspendisse potenti. In non enim in magna efficitur mattis sed quis urna. Etiam facilisis et sem eu ornare. Pellentesque tempus tincidunt velit, in mollis lorem faucibus eu. Quisque ac erat vitae lorem faucibus placerat. Cras lectus orci, blandit vitae laoreet nec, hendrerit in est. Cras eu tellus mollis, condimentum justo eu, dapibus libero. Ut et aliquam diam, id consectetur lacus.

<br><p>
Suspendisse mattis scelerisque metus, non vehicula urna finibus sed. Maecenas consectetur consectetur convallis. Suspendisse sapien quam, tristique in ipsum vel, vestibulum luctus justo. Nunc risus eros, varius vel iaculis at, pharetra luctus nisl. Donec interdum, ante eu varius tincidunt, enim tellus vehicula quam, at mattis nunc ipsum vel libero. Sed condimentum enim sed justo vulputate luctus. Praesent vel leo eu est scelerisque vehicula. Nulla faucibus elit vitae gravida malesuada. Vestibulum iaculis, urna vitae aliquet sollicitudin, ligula magna ullamcorper ipsum, id gravida mauris mi at ex. Nulla ac ante felis. Fusce vitae mattis nisl, ut interdum purus.

<br><p>
Vivamus mollis nunc a erat tempor, et auctor ante dapibus. Integer nulla ipsum, commodo sit amet purus sit amet, elementum tincidunt velit. Curabitur auctor et sapien at accumsan. Nam vestibulum nunc elit, quis ullamcorper quam bibendum a. Sed posuere, dolor ut euismod rutrum, purus diam laoreet neque, eget auctor lacus lacus in erat. Aenean quam risus, rhoncus eu eleifend sit amet, imperdiet at sapien. Aenean faucibus lectus lectus, eget lobortis lacus laoreet sed. Donec vestibulum ut lorem ac tincidunt.

<br><p>
Donec commodo sagittis metus. Proin imperdiet porta cursus. Vestibulum gravida odio vel risus finibus scelerisque. Vivamus scelerisque, nibh a placerat egestas, ante nulla gravida purus, sed mattis lectus nulla vitae elit. Nunc commodo et dolor quis bibendum. Morbi porttitor convallis enim vitae ornare. Sed dignissim dolor ut leo aliquet, et euismod massa facilisis. Curabitur ipsum sapien, viverra et elementum et, suscipit eu ligula. Pellentesque lobortis lectus suscipit elementum faucibus. Integer mattis neque id lorem congue mollis. Fusce congue odio quis lorem sagittis, vel venenatis quam bibendum. Fusce risus urna, vulputate in cursus quis, molestie ac purus. Etiam ornare maximus est, sit amet tristique arcu porta nec. Suspendisse non molestie lorem, non egestas libero.

<br><p>
Aliquam suscipit placerat semper. Nam accumsan massa elit, quis pulvinar enim tincidunt non. Vestibulum ut felis sit amet urna semper maximus eget ac nulla. Phasellus placerat leo in urna malesuada, a tempus urna dapibus. Donec ac metus mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent gravida vitae dui nec dictum. Pellentesque vitae vehicula felis, in eleifend enim. Cras eget ex id odio viverra pellentesque sed et justo. Integer convallis at ante ac vestibulum. Praesent sit amet faucibus elit, non pulvinar eros. Cras vel nunc turpis. Donec quis placerat magna, sit amet feugiat metus. Maecenas pulvinar nulla id orci pretium efficitur.

<br><p>
In condimentum sed eros sed semper. In hac habitasse platea dictumst. Aenean viverra, mi et convallis cursus, felis metus tristique elit, et venenatis lectus nibh sit amet ligula. Donec at magna aliquam, finibus dui eu, ultrices risus. Morbi consectetur sem non ligula sodales facilisis. Ut lacinia mauris ante, nec suscipit metus tempor non. Nulla gravida pretium porta. Proin sit amet augue maximus, ultrices turpis in, hendrerit odio. Cras quis tortor sit amet mi ultricies ultrices. Maecenas vel fermentum justo. Donec porta nisi sed nulla tempus, eu volutpat tortor ultrices.

<br><p>
Duis euismod pharetra rutrum. Pellentesque leo dui, ultricies eget vehicula id, sollicitudin sit amet velit. Vivamus justo nibh, volutpat sit amet eros tincidunt, sagittis porta nunc. Vestibulum vitae accumsan mi. Pellentesque porttitor vitae orci eu fringilla. Integer accumsan ante vitae eros vulputate, at efficitur est tincidunt. Donec viverra quam a turpis pellentesque vehicula. Curabitur ac vestibulum tellus. Aenean ut nulla auctor, mollis ex nec, commodo diam. Sed lacus libero, rutrum in nunc eu, ornare tincidunt urna. Aliquam tristique, arcu ac tempus tincidunt, ligula ante varius magna, non ultricies arcu velit et mi. Praesent varius eros in congue tempor.

<br><p>
Pellentesque fringilla, erat et viverra rutrum, nulla lectus dapibus ante, sed eleifend sem quam sit amet risus. Fusce sit amet est massa. Suspendisse potenti. Fusce sed pellentesque urna. Duis sapien ipsum, pretium in eleifend at, mollis in lacus. Suspendisse ullamcorper odio velit, imperdiet tristique leo auctor vitae. Maecenas pulvinar consequat pretium. Nam facilisis elementum lorem, nec iaculis sem laoreet sed. Maecenas vel turpis neque. Nam at dictum neque. Donec auctor vitae lacus quis dictum.

<br><p>
Cras id enim lorem. Quisque sit amet dui varius, euismod nulla pretium, aliquet urna. Maecenas sodales magna vel diam placerat ullamcorper. Nunc ut vulputate nulla. Aenean nec justo nec quam mattis tristique. Suspendisse nibh lorem, efficitur sed massa sit amet, pretium porta diam. Curabitur iaculis venenatis nisi quis accumsan. Pellentesque ac sapien lacus. Mauris ultricies rutrum orci, vel lobortis ante vehicula non. Etiam pretium velit mauris, a facilisis risus vestibulum at. Aenean pharetra ipsum diam. Nulla et odio ut leo tristique ornare non nec odio.

<br><p>
Sed eu tempor eros. Pellentesque tristique ex vel egestas varius. Aliquam in vestibulum massa. Suspendisse scelerisque arcu lorem, eget sodales magna tempor molestie. Curabitur bibendum ex nunc, non dictum neque commodo eu. Phasellus dictum a lorem vel placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris lectus ex, faucibus in dolor sed, dignissim ornare quam. Aliquam a placerat urna, eget pellentesque elit. Proin ultrices tempus odio, ac commodo felis commodo id. Sed pellentesque, massa nec posuere dapibus, libero sapien bibendum risus, a rutrum nunc sem in tortor. In sed ipsum at turpis scelerisque tristique. Integer eleifend mauris in sem congue interdum. Nunc a venenatis est. Ut sed nisl vel ligula interdum ornare nec vel nisi. Morbi ante tortor, bibendum id enim sed, vulputate faucibus quam.

<br><p>
Phasellus blandit feugiat porta. Vestibulum imperdiet quis lectus eu semper. Vivamus ac sagittis arcu. Ut arcu risus, egestas vel dolor ac, sagittis fringilla purus. Ut lacinia nunc sed ex iaculis lacinia. Morbi nec condimentum sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin euismod condimentum nulla, at aliquet enim convallis in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sit amet vehicula nisi. Sed molestie cursus rhoncus. Curabitur auctor metus quis tempus elementum. Curabitur neque nibh, interdum a iaculis quis, blandit at felis. Ut nec ante nec orci tempus efficitur.

<br><p>
Donec varius lorem est, non pulvinar augue convallis eu. Proin malesuada enim ipsum, vel tempor ante vestibulum a. Phasellus nec arcu in arcu venenatis porttitor at a nibh. Integer non ante luctus, luctus orci et, consequat felis. Proin a metus eget justo scelerisque condimentum. Maecenas volutpat suscipit pulvinar. Nam eu metus eros. Pellentesque blandit ex a dignissim hendrerit. Morbi nec ipsum risus. Phasellus non posuere leo, eleifend maximus felis. Maecenas ut eleifend ipsum, eu sollicitudin purus. Vivamus sit amet iaculis ante. Donec eu eleifend orci, non convallis magna. Sed ut ipsum ipsum. Aliquam ut dui at erat faucibus venenatis et sit amet dui. Morbi porttitor eleifend posuere.

ScrapLocker/app/views/users/index.html.erb
<h1>Users#index</h1>

ScrapLocker/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<ul>
    		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
			</li>
			<li>
			<%= f.label :email %>
			<%= f.text_field :email %>
			</li>
			<li>
			<%= f.label :password %>
			<%= f.password_field :password %>
			</li>
			<li>
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			</li>
			<li>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
			</li>
      	</ul>
    <% end %>
  </div>
</div>

ScrapLocker/app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= link_to "Sign out", signout_path, method: "delete" %>